name: 🚀 Deploy website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: 🚀 Deploy website
    runs-on: ubuntu-latest
    env:
        HUGO_VERSION: 0.114.0
    steps:
    - name: Install Hugo CLI
      run: |
        wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
        && sudo dpkg -i ${{ runner.temp }}/hugo.deb 
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.4.0
    - name: Build with Hugo
      env:
        HUGO_ENVIRONMENT: production
        HUGO_ENV: production
      run: |
        hugo \
          --gc \
          --minify       
    - name: 🚢 Ship it!
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        local-dir: ./public/
        server: ${{ secrets.FTP_SERVER }}
        protocol: ftps
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
